services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual (.)
    build: .
    # Nome do container
    container_name: gestao-escolar-api
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000" # Sobrescreve o CMD do Dockerfile para habilitar o --reload, ótimo para desenvolvimento
    # Mapeia o diretório atual para /app dentro do contêiner.
    # Isso permite que as alterações no código sejam refletidas imediatamente e que o banco de dados (escola.db) seja salvo no seu computador.
    volumes:
      - .:/app
    #command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
